version: "1"
services:
  app:
    build:
      context: ./
      dockerfile: dockerfile
    restart: unless-stopped
    ports:
      - "8085:8085"
    volumes:
      - ./:/var/www
    depends_on:
      - mdfebumk-db
    environment:
      DB_HOST: mdfebumk-db
      DB_PORT: 3306
      DB_DATABASE: mdfebumk
      DB_USERNAME: mdfebumk
      DB_PASSWORD: MLtalBcE867g
    networks:
      - mdfebumk

  mdfebumk-db:
    image: mysql:8.0
    container_name: mdfebumk-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mdfebumk
      MYSQL_ROOT_PASSWORD: MLtalBcE867g
      MYSQL_PASSWORD: MLtalBcE867g
      MYSQL_USER: mdfebumk
    volumes:
      - ./mdfebumk-compose/mysql:/docker-entrypoint-initdb.d
      - ./mdfebumk-compose/mysql/logs:/var/log/mysql
      - ./mdfebumk-compose/mysql/data:/var/lib/mysql
    networks:
      - mdfebumk

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: mdfebumk-phpmyadmin
    ports:
      - 7075:80
    links:
      - mdfebumk-db
    restart: unless-stopped
    environment:
      PMA_HOST: mdfebumk-db
      PMA_USER: mdfebumk
      PMA_PASSWORD: MLtalBcE867g
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - mdfebumk

networks:
  mdfebumk:
    driver: bridge
