
name: Deploy Web MD Febi UMK
on:
  push:
    # branches: [ development ]
    branches: [ master ]
    paths:
      - 'app/**'
      - 'bootstrap/**'
      - 'config/**'
      - 'database/**'
      - 'resources/**'
      - 'routes/**'
      - 'storage/**'
      - 'test/**'
      - '.editorconfig'
      - '.env.example'
      - '.gitattributes'
      - '.gitignore'
      - 'artisan'
      - 'composer.json'
      - 'composer.lock'
      - 'composer.lock'
      - 'package.json'
      - 'phpunit.xml'
      - 'README.md'
      - 'vite.config.js'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Here is the deployment action
      - name: Upload from laravel mdfebumk via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}